users:
- email: afolabi.fajobi1@gmail.com
  first_name: afolabi
  last_name: fajobi
  groups:
  - jit-requesters
- email: charles123@gmail.com
  first_name: charles
  last_name: ade
  groups:
  - jit-requesters